### ISSUE TITLE
GPL infringement

### ISSUE THREAD

**Issue by bmustiata** [Mikej81/WebRDP#5]
https://github.com/Mikej81/WebRDP/blob/4b120ddd8671c9204eb07484047000cee121116e/client/js/canvas.js#L7

Hi, it seems that you're infringing GPL. You can't license your code as MIT if you're using sources that are GPL.

**Comment by Mikej81** [comment]
All better!

**Comment by bmustiata** [comment]
You should probably also remove https://github.com/Mikej81/WebRDP/blob/master/LICENSE-MIT and replace it with GPL. Github detects currently the license from the LICENSE file, not your README.
